name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-test-codebuild-with-github-actions-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"